### ISSUE TITLE
Test on Pretrained model got incorrect results

### ISSUE THREAD

**Issue by deng-wei** [yzhouas/PD-Denoising-pytorch#1]
I just  simiply run `bash run_test_on_real_patches.sh` .
hard_human_512_pss2_k0.0.png
![hard_human_512_pss2_k0 0](https://user-images.githubusercontent.com/8124973/57348687-9c678900-7189-11e9-8472-a5dcc16fadae.png)
crop8_pss2_k0.0.png
![crop8_pss2_k0 0](https://user-images.githubusercontent.com/8124973/57348769-e0f32480-7189-11e9-9b2e-33c7ca2d50a7.png)

**Comment by yzhouas** [comment]
Thanks for pointing it out. I fixed the bugs in the test script. Now it should work.
